lib/generators/rodauth/install_generator.rb, lib/generators/rodauth/mailer_generator.rb, lib/generators/rodauth/views_generator.rb, lib/rodauth/rails.rb, lib/rodauth/rails/feature.rb, test/test_helper.rb
This makes CSRF protection with Rails follow the same rules as when using Roda directly, meaning users can do things like override `#check_csrf?` to skip CSRF protection for certain routes, and that will now work correctly with rodauth-rails. The rodauth-oauth gem is one example where CSRF protection needs to be skipped for some routes.
We first need to wait for https://github.com/jeremyevans/rodauth/pull/96 to be merged, which adds the `#check_csrf` method.
Closes #2
/cc @HoneyryderChuck
=> Use Rodauth's new #check_csrf method for CSRF protection

.travis.yml, Gemfile, gemfiles/Gemfile.rails-5.2, gemfiles/Gemfile.rails-6.0, lib/generators/rodauth/install_generator.rb, lib/generators/rodauth/templates/config/initializers/sequel.rb, test/generators/install_generator_test.rb, test/rails_app/config/initializers/sequel.rb
Now that sequel-activerecord_connection gem supports JRuby, we configure Travis CI to test rodauth-rails on JRuby as well.
=> Test on JRuby

README.md
=> Use consistent name in "multiple configurations" examples in README

lib/generators/rodauth/migration/base.erb, test/rails_app/db/migrate/20200411171322_create_rodauth.rb
Fixes Issue #27 
Change default account status to 'unverified' and reordered unique where status in constraint to match Rodauth default table setup: http://rodauth.jeremyevans.net/rdoc/files/README_rdoc.html#label-Creating+tables
=> Fix default account status

lib/rodauth/rails/app.rb
Hey,
I noticed that for fresh Rails 6.1.2 app in api-only mode error from https://github.com/janko/rodauth-rails/issues/13 is still present.
```ruby
NoMethodError (undefined method `flash' for #<ActionDispatch::Request:0x00007fe26ad93600>):
```
This is because `ActionDispatch::Flash` is existing constant in the app, but it doesn't included in Request:
```ruby
$ rails c
Loading development environment (Rails 6.1.2)
[1] pry(main)> defined? ActionDispatch::Flash
=> "constant"
[2] pry(main)> ActionDispatch::Request.ancestors.include?(ActionDispatch::Flash::RequestMethods)
=> false
```
This PR changes rails api-only check so it'll rely on Rails configuration instead of defined constants.
Hope this help someone like me!
=> Fix rails api-only check

README.md
I'm integrating `rodauth-rails` in a new project, and I was confused about the way multiple accounts configuration is working.
Thanks to [rodauth's documentation][1] I was able to add the required parameters.
[1]: http://rodauth.jeremyevans.net/rdoc/files/doc/base_rdoc.html
=> Add more params to multi configuration

CHANGELOG.md, lib/rodauth/rails/feature.rb, lib/rodauth/rails/log_subscriber.rb, lib/rodauth/rails/railtie.rb, test/integration/json_test.rb, test/integration/logging_test.rb
The `Rails::Rack::Logger` middleware already logs each request on the URL level, and view rendering is being logged as well. However, requests to controller actions also display:
```
Processing by MyController#some_action as HTML
Completed 200 OK in 12ms (...more info...)
```
We want the same kind of nice logging for Rodauth requests, to communicate to the developer that the RodauthApp middleware has indeed caught the request, what was response status, and how long the whole request took.
We implement this using the same approach that Action Pack uses to implement controller-level logging. Now the developer sees this for a Rodauth request:
```
Started GET "/create-account" for 127.0.0.1 at 2021-05-06 17:46:12 +0200
Processing by RodauthApp as HTML
Completed 200 OK in 15ms (ActiveRecord: …
```
=> Add controller-like request logging

lib/rodauth/rails/feature/render.rb
`ActionView::LookupContext` will by default look up templates in all known formats (33 of them). This results in quite a few system calls, which can slow down rendering, especially when filesystem access is slower (e.g. when using macOS with Docker).
Before processing an action, Action Controller reduces the list of formats only to formats that the current request accepts. However, rodauth-rails is rendering templates outside of action processing, so this code is not being executed. We fix this by calling it manually.
Fixes #48
=> Speed up rendering by limiting template formats

lib/rodauth/rails/feature/internal_request.rb
Pass block to super in `internal_request` override, which is necessary to support [`internal_request_eval`](https://github.com/jeremyevans/rodauth/commit/6d482203af6e2bf662d094f1c8546793ab910738).
=> Support `internal_request_eval`

README.md, gemfiles/Gemfile.rails-5.0, lib/generators/rodauth/templates/app/models/account.rb, lib/rodauth/rails.rb, lib/rodauth/rails/model.rb, lib/rodauth/rails/model/associations.rb, rodauth-rails.gemspec, test/model_test.rb, test/rails_app/app/models/account.rb, test/rails_app/db/migrate/20200411171322_create_rodauth.rb
Currently, creating an account with a password programmatically is a bit cumbersome, mostly due to bcrypt-hashing, especially when the password is stored in a separate table. This adds friction in development and in tests, and also for anyone wanting to implement simple user creation by admins. Devise, Sorcery, and has_secure_password all provide this level
of convenience.
Additionally, there are cases where it's useful to be able to directly query associated tables (e.g. retrieving all accounts that have MFA enabled), and it might not be obvious how to declare associations, e.g:
```rb
class Account < ApplicationRecord
has_one :remember_key, foreign_key: :id
end
class Account::RememberKey < ApplicationRecord
end
```
To address this friction, we add a `Rodauth::Rails::Model` mixin that can …
=> Add Rodauth::Rails::Model for Active Record integration

README.md, lib/generators/rodauth/views_generator.rb, lib/rodauth/rails.rb, lib/rodauth/rails/feature.rb, lib/rodauth/rails/feature/callbacks.rb, lib/rodauth/rails/feature/internal_request.rb, lib/rodauth/rails/tasks.rake, rodauth-rails.gemspec, test/internal_request_test.rb, test/rails_app/app/lib/rodauth_app.rb, test/rails_app/app/models/account.rb, test/rodauth_test.rb, test/test_helper.rb
This adds support for the upcoming internal_request Rodauth feature. The following changes are made for internal requests:
* base URL defaults are picked up from `config.action_mailer.default_url_options`
* controller callbacks and rescue handlers are skipped during internal requests
* view rendering is skipped during internal requests
* controller instrumentation is skipped during internal requests
In the future we might deprecate the `Rodauth::Rails.rodauth` API for creating Rodauth instances in favour of the internal_request feature, but for now we just add a note to the README.
The tests also need to be added before merging.
=> Support internal_request feature

README.md, lib/rodauth/rails/railtie.rb, lib/rodauth/rails/test.rb, lib/rodauth/rails/test/controller.rb, test/controllers/test_controller_test.rb, test/rails_app/app/models/account.rb, test/test_helper.rb
This allows controllers calling Rodauth to be controller-tested, via `ActionController::TestCase` that's internally used by RSpec's controller specs. It ensures Rodauth instance(s) are set in request env, converts Rodauth responses into controller responses, and provides the `#rodauth` method.
```rb
class ArticlesController < ApplicationController
before_action -> { rodauth.require_authentication }
def index
@articles = current_account.articles.all
end
end
```
```rb
class ArticlesControllerTest < ActionController::TestCase
test "authentication" do
get :index
assert_response 302
assert_redirected_to rodauth.login_path
account = Account.create(email: "user@example.com", password: "secret", status: "verified")
login(account)
get :index
assert_response 200
end
private
def login(account) …
```
=> Add controller test integration

lib/generators/rodauth/migration/sequel/base.erb
As noted here:
> It's trivial to use run "CREATE EXTENSION citext" in your migration if you want to add the extension.
https://github.com/jeremyevans/sequel/pull/819#issuecomment-43821533
Note enable_extension uses "IF NOT EXISTS", as per:
https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter.html#method-i-enable_extension
=> Don't use enable_extension under Sequel, which doesn't support it

CHANGELOG.md, lib/rodauth/rails/app.rb, lib/rodauth/rails/feature/instrumentation.rb
The newrelic_rpm gem expects `:controller` in instrumentation event payload to point to an actual Rails controller, so it tries calling `controller_path` on it. I considered putting the Rodauth controller there, but I found it misleading, since it's the Rodauth application processing the request, the Rodauth controller is only doing view rendering. In the end I decided to just define a `controller_path` method on the Rodauth app.
Closes #119
=> Support newrelic_rpm gem instrumentation

lib/generators/rodauth/install_generator.rb, lib/generators/rodauth/templates/app/test/fixtures/accounts.yml, test/generators/install_generator_test.rb
* PR for adding fixtures.
* Assumes folks will be using an `Account` name. This is hard coded.
* Fixtures placed in `test/fixtures` location as per convention.
* I made assumptions about how the hash will be created. It may be incorrect.
I want to automatically create user accounts as fixtures, so I can run request specs without creating accounts on the fly:
```rb
account = Account.create(email: ....etc) #
login(account)
account  = accounts(:one) # fixtures
login(account) # preferably using the same login params used by rodauth
def login(account)
post "/login", params: {"login"=>"brian@queen.com", "password"=>"password"}
end
```
(By the way, is there any way of getting a hold of a rodauth object in tests so we can write?
```rb
post rodauth.login_path # etc.
```
I hope this is …
=> Add: fixtures

lib/rodauth/rails/feature/base.rb, test/integration/base_test.rb
Fix for [rails_account not returning nil](https://github.com/janko/rodauth-rails/discussions/138)
Not sure if this is the implementation desired, or whether I am testing adequately: pls do not hesitate to send back any changes required.
=> fix: bug - rails_account should return nil when logged_in? == false

.gitignore, lib/generators/rodauth/templates/app/misc/rodauth_main.rb
Providing `verify_account_grace_period` as `ActiveSupport::Duration` does not work with` jwt` feature enabled.
During JWT encode/decode process it will be converted to string
```ruby
token = JWT.encode({ unverified_account: 3.days }, Rails.application.secret_key_base)
JWT.decode(token, Rails.application.secret_key_base)
token = JWT.encode({ unverified_account: 3.days.to_i }, Rails.application.secret_key_base)
JWT.decode(token, Rails.application.secret_key_base)
```
while [Rodauth expects integer](https://github.com/jeremyevans/rodauth/blob/859de3a9e3a74a1449a881f7d269516ff8c25831/lib/rodauth/features/verify_account_grace_period.rb#L90).
I was thinking about adding this to generator only if `jwt` feature is enabled but I think it could lead to unexpected situations if jwt is enabled after …
=> Verify account grace period generator fix

README.md
Fixes #178 
Emphasized a strategy for testing with login/logout helpers with a brief example in the Rails-promoted style of `ActionDispatch::IntegrationTest` tests. Moved information about `ActionController::TestCase` style tests into the wiki since that has been deprecated, though still in wide use.
=> Rewrite Testing section of README

README.md
The stream on how to add admin accounts is handy for new users -  i think it would be useful to list it here.
(I stumbled upon it purely by accident)
=> docs: add live stream recording link

lib/generators/rodauth/views_generator.rb, test/generators/views_generator_test.rb
PR adds an ability to generate Rails view for Confirm Password feature (https://rodauth.jeremyevans.net/rdoc/files/doc/confirm_password_rdoc.html).
=> Added confirm_password feature to views generator

README.md
I found the link to `How to build an OIDC provider using rodauth-oauth on Rails` was no longer valid, so I made a slight update on it.
=> Update OIDC guideline's link

lib/generators/rodauth/migration/active_record/audit_logging.erb, lib/generators/rodauth/migration/sequel/audit_logging.erb
This PR resolves https://github.com/janko/rodauth-rails/issues/305
The hardcoded id name is causing conflicts when used with multiple accounts.
Since rodauth does not rely on this index name, we are removing it completely and relying the default generated by rails.
Migrated table sample
=> remove redudant index name: audit_at_idx
